### PR TITLE
[kitsune] Fix list of statically linked libraries

### PR DESCRIPTION
**Pull request by jsarrao**
These changes are necessary if `LLVM_LINK_LLVM_DYLIB=false`

### CODE REVIEW

**Review by pmccormick — APPROVED** [review]

**Comment by stelleg** [comment]
@tarunprabhu I'm a little late, but I think these are not the fixes we want. I'm pretty confident my patch is the better way to fix all the errors these are addressing.

**Comment by tarunprabhu** [comment]
Sorry, I meant to look at your PR and I got caught up trying to fix my cmake mess. I thought that Joseph's issues were a superset of yours, but weirdly, they are not.

I have reviewed your PR. If you could remove the HipABI.cpp changes that are in there, we can merge it in.

**Comment by stelleg** [comment]
Just to be clear, I think these should be reverted. While it's great that they worked for those use cases, the changes from https://github.com/lanl/kitsune/pull/49 are the correct way of adding linking dependencies. Note that all of the additions of `LLVMTapirOpts` are on links requiring `clangFrontend`, and the addition of `Passes` occurs when linking with `TapirOpts`.

**Comment by tarunprabhu** [comment]
Ah, right. I see. I agree that #49 is a better fix. We should revert this.

**Pull request merged**
