### PR TITLE
Realm 10.x

### PR DESCRIPTION
**Pull request by pmccormick**
Updated PR #28 to patch build issue.  

Please re-test.  Thx.

### CODE REVIEW

**Comment by stelleg** [comment]
Now seeing the following error: 
```
In file included from /home/george/kitsune/clang/kitsune/examples/kokkos/vecadd.cpp:15:
In file included from /usr/local/include/Kokkos_Core.hpp:58:
In file included from /usr/local/include/Kokkos_OpenMP.hpp:210:
/usr/local/include/OpenMP/Kokkos_OpenMP_Exec.hpp:52:2: error: "You enabled Kokkos OpenMP support without enabling OpenMP in the compiler!"
#error \
```

**Comment by pmccormick** [comment]
This reflects a dependency on how you built your local version of Kokkos.  There's currently no easy way for us to sort this out within our build system -- the only option I am aware of at this point is to customize your own build flags for the kokkos examples to include `-fopenmp`.   I'd suggest we punt on this for this PR and revisit as part of the next milestone release.

**Comment by AlexisPerry** [comment]
> This reflects a dependency on how you built your local version of Kokkos. There's currently no easy way for us to sort this out within our build system -- the only option I am aware of at this point is to customize your own build flags for the kokkos examples to include `-fopenmp`. I'd suggest we punt on this for this PR and revisit as part of the next milestone release.

In light of this, should I change kitsune-dev.cmake to NOT build the examples by default?  Or is it ok as is?

**Comment by pmccormick** [comment]
I'll fix the default for building the examples and push it up -- easiest since I started this PR.

**Pull request merged**
